### PR TITLE
resized some vectors and added a few reference values

### PR DESCRIPTION
**Pull request by kgasperich**
updates from call today

### CODE REVIEW

**Comment by kgasperich** [comment]
I added a second walker where I shift the first electron by the same amount in the y direction (instead of x)
I had assumed that it started at (0,0,0), but maybe this is incorrect?
If they both start at the position of the ion, then the MOs for the second walker should have the same value and laplacian, and the grad_x/grad_y should switch but have the same value.

**Comment by kgasperich** [comment]
I added a new test with `nAO, nMO > 1` and `nAO != nMO`.
I think there's still something causing some undefined behavior, but I haven't figured out what it is yet.
For the single-walker interface, I [check the vgl](https://github.com/kgasperich/qmcpack/blob/aec175904bce1382f0294b552fcefc563606d877/src/QMCWaveFunctions/tests/test_MO.cpp#L351-L407) for the first two MOs at positions of [0.0001,0,0] and [0, 0.04, 0.02] (results stored in `{,d,d2}psiref_{0,1}`).
For the multi-walker interface, I place electron 0 of walker 0 at [0.0001,0,0] and electron 0 of walker 1 at [0, 0.04, 0.02].
When I try to test by asserting that the new vgl elements are the same as the ones in the vectors that I filled with the single-walker interface (psiref_0, psiref_1, etc.), then it looks like those values have changed (the assertions [here](https://github.com/kgasperich/qmcpack/blob/aec175904bce1382f0294b552fcefc563606d877/src/QMCWaveFunctions/tests/test_MO.cpp#L443-L445) fail even though they are the same as the lines above, and I don't think I've touched `psiref_{0,1}` since then).
Sometimes the test will pass, sometimes it will fail the second (identical) check, and there also seems to be a memory management problem, because sometimes I get `free(): invalid next size (fast)`, `munmap_chunk(): invalid pointer`, or `corrupted double-linked list` (and sometimes it just throws a segfault without one of these three messages).
I'll try using a sanitizer to see if that helps to find the issue.

**Comment by kgasperich** [comment]
It was an issue with `OrbitalSetSize` vs `BasisSetSize`.

The remaining issue is that the gradients aren't correct (I suspect that it is in the copying from the list of gradvectors back to the relevant part of the OffloadMWVGLArray, but if it's an incorrect assumption about memory layout that I've made then there might also be an issue with the gemm call).

**Comment by kgasperich** [comment]
I fixed the grad copying.
They're `[dim, walker, orb]` in the `OffloadMWVGLArray` and `[walker][orb, dim]` in `RefVector<GradVector>`, so we just needed a dim-length stride for the grad vector (inside the loop over walkers)

**Comment by shivupa** [comment]
This looks good to me and thank you for adding and troubleshooting the nAO, nMO > 1 and nAO != nMO case.

At first I was worried about about the `BLAS::COPY` not being usable if we end up moving to things stored on device, but in that case we would want to call the `mw_` funcs directly since we cant use the non `mw` variant. Seems good to go!
Thank you

**Review by shivupa — APPROVED** [review]

**Review by amandadumi — APPROVED** [review]
This looks great, thanks for fixing and expanding the tests.

**Pull request merged**
